### ISSUE TITLE
Mavenize the project

### ISSUE THREAD

**Issue by fabiojo7777777** [fabiojo7777777/httpmock#1]
Initially I did a project at eclipse IDE without any maven dependency. The .jar files are inside the project, in the lib folder and separated into folders identified by the name and version of the library used.
 
Despite having a pom.xml it is not mavenized.

The point is that there are 2 dependencies (httpcomponents-client-5.0 and httpcomponents-core-5.0), which I can't resolve with the central maven repository with the required version, so I couldn't put it in the mavenized format. I tried to do it as it is on the apache help page, but it is not solving the dependencies to do the compilation.

I downloaded these dependencies from the apache http client website itself: http://hc.apache.org/downloads.cgi, httpclient components and httpcore components version 5.0.

**Comment by fabiotavarespr** [comment]
Hello @fabiojo7777777 !

I believe the easy way to solve your problem is create a new project in Eclipse with "Create a maven project" and refactor everything.

I'll try to help you on this journey.

**Comment by jairsjunior** [comment]
Hi @fabiojo7777777, how is going?
Looking here, you need to remove this dependencies at your `pom.xml`
```
        <dependency>
	        <groupId>org.apache.httpcomponents.core5</groupId>
		<artifactId>httpcore5</artifactId>
		<version>5.0</version>
		<type>pom</type>
	</dependency>
	<dependency>
		<groupId>org.apache.httpcomponents.client5</groupId>
		<artifactId>httpclient5-parent</artifactId>
		<version>5.0</version>
		<type>pom</type>
	</dependency> 
```
And add this one
```
        <dependency>
		<groupId>org.apache.httpcomponents.client5</groupId>
		<artifactId>httpclient5</artifactId>
		<version>5.0.1</version>
	</dependency>
```

Running here works as expected, can you try and say if worked? And i created the project here importing as new maven project so everything works properly.

**Comment by fabiojo7777777** [comment]
Hi @jairsjunior 
Grateful by your comment and yes, your solution works, but as I also added dependencies in the eclipse build path, it was also necessary to pull them out to be fully mavenized according to @fabiotavarespr pull request solution

**Comment by fabiojo7777777** [comment]
Issue solved
